-- ═══════════════════════════════════════════════════════════════
-- Actions Module — schema, indexes, FKs, RLS, triggers
-- شغّلي الملف ده مرة واحدة في Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- ─── جدول الأكشنات ─────────────────────────────────────────────
create table if not exists public.actions (
  id                bigint generated by default as identity primary key,
  line_number       text not null,
  client_id         bigint references public.clients (id) on delete set null,
  action_type       text not null check (action_type in (
                      'customer_request', 'cancellation', 'migration',
                      'package_change', 'sim_replacement', 'follow_up',
                      'payment_reminder', 'customer_complaint', 'other'
                    )),
  title             text not null,
  description       text,
  priority          text not null default 'medium' check (priority in (
                      'low', 'medium', 'high', 'urgent'
                    )),
  status            text not null default 'pending' check (status in (
                      'pending', 'in_progress', 'completed', 'cancelled'
                    )),
  start_date        date,
  due_date          date not null,
  completed_date    date,
  completion_notes  text,
  assigned_user_id  bigint references public.users (id) on delete set null,
  notes             text,
  created_by        text,
  completed_by      text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  notification_sent boolean not null default false
);

-- ─── جدول الإشعارات ────────────────────────────────────────────
create table if not exists public.notifications (
  id          bigint generated by default as identity primary key,
  action_id   bigint references public.actions (id) on delete cascade,
  user_id     bigint references public.users (id) on delete cascade, -- null = للجميع
  kind        text not null check (kind in (
                'due_today', 'overdue', 'high_priority', 'completed',
                'due_tomorrow', 'general'
              )),
  title       text not null,
  description text,
  is_read     boolean not null default false,
  created_at  timestamptz not null default now()
);

-- ─── Indexes ───────────────────────────────────────────────────
create index if not exists idx_actions_line_number   on public.actions (line_number);
create index if not exists idx_actions_status        on public.actions (status);
create index if not exists idx_actions_priority      on public.actions (priority);
create index if not exists idx_actions_action_type   on public.actions (action_type);
create index if not exists idx_actions_due_date      on public.actions (due_date);
create index if not exists idx_actions_client_id     on public.actions (client_id);
create index if not exists idx_actions_assigned_user on public.actions (assigned_user_id);
-- استعلام الوجبات المجدولة: أكشنات لسه شغالة وقرب/فات معادها ولسه متبعتلهاش إشعار
create index if not exists idx_actions_open_due
  on public.actions (due_date, status) where status in ('pending', 'in_progress');

create index if not exists idx_notifications_user_read on public.notifications (user_id, is_read);
create index if not exists idx_notifications_action    on public.notifications (action_id);
create index if not exists idx_notifications_created   on public.notifications (created_at desc);

-- ─── Trigger: تحديث updated_at تلقائياً ────────────────────────
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_actions_updated_at on public.actions;
create trigger trg_actions_updated_at
  before update on public.actions
  for each row execute function public.set_updated_at();

-- ─── Trigger: إشعار تلقائي عند إنشاء أكشن بأولوية عالية/عاجلة ──
create or replace function public.notify_on_action_insert()
returns trigger language plpgsql as $$
begin
  if new.priority in ('high', 'urgent') then
    insert into public.notifications (action_id, user_id, kind, title, description)
    values (
      new.id, new.assigned_user_id, 'high_priority',
      'أكشن بأولوية ' || case when new.priority = 'urgent' then 'عاجلة' else 'عالية' end,
      new.title || ' — خط ' || new.line_number
    );
  end if;
  if new.due_date = current_date then
    insert into public.notifications (action_id, user_id, kind, title, description)
    values (
      new.id, new.assigned_user_id, 'due_today',
      'أكشن مستحق اليوم',
      new.title || ' — خط ' || new.line_number
    );
  end if;
  return new;
end $$;

drop trigger if exists trg_actions_notify_insert on public.actions;
create trigger trg_actions_notify_insert
  after insert on public.actions
  for each row execute function public.notify_on_action_insert();

-- ─── Trigger: إشعار تلقائي عند اكتمال أكشن ─────────────────────
create or replace function public.notify_on_action_complete()
returns trigger language plpgsql as $$
begin
  if new.status = 'completed' and old.status is distinct from 'completed' then
    insert into public.notifications (action_id, user_id, kind, title, description)
    values (
      new.id, new.assigned_user_id, 'completed',
      'تم إكمال أكشن',
      new.title || ' — خط ' || new.line_number
        || coalesce(' — بواسطة ' || new.completed_by, '')
    );
  end if;
  return new;
end $$;

drop trigger if exists trg_actions_notify_complete on public.actions;
create trigger trg_actions_notify_complete
  after update on public.actions
  for each row execute function public.notify_on_action_complete();

-- ─── RLS ───────────────────────────────────────────────────────
-- ملاحظة: المشروع بيستخدم anon key مع نظام دخول مخصص (localStorage)،
-- فالسياسات هنا بتسمح بالقراءة/الكتابة زي باقي جداول المشروع.
alter table public.actions enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "actions_select" on public.actions;
create policy "actions_select" on public.actions for select using (true);

drop policy if exists "actions_insert" on public.actions;
create policy "actions_insert" on public.actions for insert with check (true);

drop policy if exists "actions_update" on public.actions;
create policy "actions_update" on public.actions for update using (true);

drop policy if exists "actions_delete" on public.actions;
create policy "actions_delete" on public.actions for delete using (true);

drop policy if exists "notifications_select" on public.notifications;
create policy "notifications_select" on public.notifications for select using (true);

drop policy if exists "notifications_insert" on public.notifications;
create policy "notifications_insert" on public.notifications for insert with check (true);

drop policy if exists "notifications_update" on public.notifications;
create policy "notifications_update" on public.notifications for update using (true);

drop policy if exists "notifications_delete" on public.notifications;
create policy "notifications_delete" on public.notifications for delete using (true);
